### ISSUE TITLE
Roadmap to v0.1

### ISSUE THREAD

**Issue by srilman** [Bodo-inc/denali#1]
### Features

- Finish Implementing All Major Endpoints
  - [ ] https://github.com/Bodo-inc/denali/issues/3
  - [ ] https://github.com/Bodo-inc/denali/issues/4

###  Bug Fixes
- [ ] https://github.com/Bodo-inc/denali/issues/2
